FROM microsoft/dotnet:2.1-sdk-alpine AS build-env
WORKDIR /app

COPY . .

WORKDIR .
RUN dotnet restore

RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-aspnetcore-runtime-alpine
COPY --from=build-env /app/out ./app/
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80
ENTRYPOINT ["dotnet", "cognitocoreapi.dll"]